name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run tests with coverage (min. 92%)
      run: |
        uv run pytest --cov=shapiq_student \
                      --cov-report=term-missing \
                      --cov-report=xml \
                      --cov-fail-under=92

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: coverage.xml
