# This workflow will try to install the shapiq_student package and see if it is importable.

name: Install & Import shapiq_student

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-import:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          activate-environment: true

      - name: Install package using uv
        run: uv pip install .

      - name: Test import
        run: uv run python -c "import shapiq_student; print('✅ shapiq_student imported successfully')"
